### ISSUE TITLE
Please move to Launch Library 2

### ISSUE THREAD

**Issue by Nosudrum** [mrfhitz/Rocket-Launch-Schedule#6]
As stated on the Launch Library website since early 2020, support for the API provided from the launchlibrary.net URL has come to an end and the API will be closing down on December 31, 2020.
Since November 1 there is a launch asking to move to its successor : Launch Library 2.

You can find more details on The Space Devs website and Discord server:
https://thespacedevs.com/
https://discord.gg/p7ntkNA

Thanks a lot,

The Space Devs team

**Comment by mrfhitz** [comment]
Thanks for the info; I will take a look at the new docs.
